# Docker compose project file
#
# 1. 
---

services:
  inventree-app:
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      #- "/etc/ssl/certs:/etc/ssl/certs:ro"
      #- "/usr/share/ca-certificates/trust-source/anchors:/etc/ssl/certs:ro"
      - "./dist:/output:rw"
    environment:
      - "TZ=America/Chicago"
      - "LC_TIME=C.UTF-8"
      - "COMPOSE_BAKE=true"
